---
# tasks file for ansible-ejbca-httpd

- name: Debug ansible-ejbca-httpd dump variables
  debug:
    msg:
      - "inventory_hostname = {{ inventory_hostname }}"
      - "groups = {{ groups }}"

- name: Install HTTPD
  include_tasks: install.yml

- name: Request TLS cert for HTTPD
  include_tasks: ca_req_cert.yml
  when: 
    - inventory_hostname in groups['eeCaServers']
    #- ejbca_type is defined
    #- ejbca_type == "CA"

- name: Configure HTTPD web server
  include_tasks: configure.yml
