---

- name: Debug CA stage by dumping variables
  debug:
    msg:
      - "ejbca_user = {{ ejbca_user }}"
      - "ejbca_group = {{ ejbca_group }}"
      - "item.caname = {{ item.caname }}"
      - "item.publishers = {{ item.publishers }}"
      - "ejbca_home = {{ ejbca_home }}"
      - "dump_dest = {{ dump_dest }}"
      - "item.publishers type_debug = {{ item.publishers|type_debug }}"
      - "item = {{ item }}"

- name: Debug CA stage 2
  debug:
    msg:
      - "add_publshers_to_cas = {{ add_publshers_to_cas }}"
  when:
    - add_publshers_to_cas is defined

- name: Stage CA to create with configdump
  template:
    src: ca-template.yml.j2
    dest: "{{ dump_dest|default( ejbca_home + '/dump/subs/certification-authorities/' + item.caname + '.yaml') }}"
    owner: "{{ ejbca_user }}"
    group: "{{ ejbca_group }}"
    mode: 0664
#     no_log: true

- name: Stage CA configdump to update with Publishers
  copy:
    src: "{{ dump_dest|default( ejbca_home + '/dump/subs/certification-authorities/' + item.caname + '.yaml') }}"
    dest: "{{ ejbca_home }}/dump/addPubToCA/certification-authorities/{{ item.caname }}.yaml"
    owner: "{{ ejbca_user }}"
    group: "{{ ejbca_group }}"
    mode: 0664  
    remote_src: yes
  when:
    - add_publshers_to_cas is defined and (item.publishers|type_debug != 'NoneType')
    - add_publshers_to_cas|bool
